# Generated by Django 6.0.4 on 2026-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_work_mode',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-site'), ('HYBRID', 'Hybrid')], max_length=10),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_experience',
            field=models.TextField(blank=True, help_text='Free-text description of previous roles and responsibilities'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.CharField(blank=True, help_text="Comma-separated skills, e.g. 'python, django, machine learning'", max_length=500),
        ),
    ]
