# Generated by Django 6.0.4 on 2026-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_profile_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
