# Generated by Django 6.0.4 on 2026-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_posting_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.BooleanField(default=False),
        ),
    ]
