# Generated by Django 6.0.4 on 2026-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_info',
            field=models.TextField(help_text='About the company (used in employer profile display)'),
        ),
    ]
